eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone:  http://localhost:9003/euerka/

server:
  port: 5000
spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
#    base-url: http://localhost:9411
    base-url: http://localhost:9001
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service
    api-b:
      path: /user-feign-api/**
      serviceId: service-feign
    api-account:
      path: /account-api/**
      serviceId: account-service
