server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mliyz/SpringcloudConfig/
          search-paths: respodev
          username: mliyz
          password: liyuzhang
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/